development:
  adapter: postgresql
  encoding: unicode
  database: waldo_development
  pool: 5
  username: waldo
  password:
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: waldo_test
  pool: 5
  username: waldo
  password:
  host: localhost
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: waldo_production
  pool: 5
  username: waldo
  password:
